name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-cd.yml"

jobs:
  dockerize-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/HospitalAPI/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hospital-management-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hospital-management-api:${{ github.sha }}

  redeploy-azure-appservice:
    runs-on: ubuntu-latest
    needs: dockerize-and-push

    steps:
      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: hospital-management-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/hospital-management-api:latest
